# Generated by Django 3.0.3 on 2020-02-26 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data_User',
            fields=[
                ('user_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('nama_user', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
                ('id_dinkes', models.CharField(max_length=30)),
                ('level', models.IntegerField()),
                ('deleted', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_Chapter',
            fields=[
                ('chapter', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_chapter', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_Kategori',
            fields=[
                ('kat', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_kat', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_Subkategori',
            fields=[
                ('subkat', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nama_subkat', models.CharField(max_length=100)),
                ('kat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Indeks',
            fields=[
                ('kode', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('deleted', models.IntegerField()),
                ('last_upload', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('kat_pasien', models.IntegerField(primary_key=True, serialize=False)),
                ('umur', models.CharField(max_length=7)),
                ('jenis_kelamin', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('kode_pkm', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_pkm', models.CharField(max_length=30)),
                ('kecamatan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasus_baru', models.IntegerField()),
                ('kasus_lama', models.IntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Subkategori')),
                ('kat_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Indeks')),
            ],
        ),
        migrations.CreateModel(
            name='Jumlah_Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.IntegerField()),
                ('gakin', models.IntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Subkategori')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Indeks')),
            ],
        ),
        migrations.AddField(
            model_name='indeks',
            name='kode_pkm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Puskesmas'),
        ),
        migrations.CreateModel(
            name='ICD10_Subchapter',
            fields=[
                ('subchapter', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_subchapter', models.CharField(max_length=30)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='icd10_kategori',
            name='subchapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Subchapter'),
        ),
    ]
