# Generated by Django 3.0.3 on 2020-02-26 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data_User',
        ),
    ]
