# Generated by Django 3.0.3 on 2020-02-26 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0002_delete_data_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puskesmas',
            name='kode_pkm',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
