# Generated by Django 3.0.3 on 2020-02-27 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0003_auto_20200226_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jumlah_kasus',
            old_name='jumlah',
            new_name='jumlah_baru_l',
        ),
        migrations.AddField(
            model_name='jumlah_kasus',
            name='jumlah_baru_p',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jumlah_kasus',
            name='jumlah_lama_l',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jumlah_kasus',
            name='jumlah_lama_p',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pasien',
            name='umur',
            field=models.CharField(max_length=10),
        ),
    ]
