# Generated by Django 3.0.3 on 2020-02-27 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0004_auto_20200227_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumlah_kasus',
            name='jumlah_baru_p',
        ),
        migrations.RemoveField(
            model_name='jumlah_kasus',
            name='jumlah_lama_l',
        ),
        migrations.RemoveField(
            model_name='jumlah_kasus',
            name='jumlah_lama_p',
        ),
    ]
