# Generated by Django 3.0.3 on 2020-03-31 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0006_auto_20200227_1333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kasus',
        ),
    ]
