# Generated by Django 3.0.3 on 2020-03-31 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0007_delete_kasus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasus_baru', models.IntegerField()),
                ('kasus_lama', models.IntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Subkategori')),
                ('kat_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Indeks')),
            ],
        ),
    ]
