# Generated by Django 3.0.3 on 2020-04-04 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0009_auto_20200401_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='kat_pasien',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pasien',
            name='umur',
            field=models.CharField(max_length=15),
        ),
    ]
