# Generated by Django 3.0.3 on 2020-04-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0010_auto_20200404_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pasien',
            name='umur',
            field=models.CharField(max_length=10),
        ),
    ]
