# Generated by Django 3.0.3 on 2020-04-10 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0011_auto_20200404_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jumlah_kasus',
            name='icd_10',
        ),
        migrations.RemoveField(
            model_name='jumlah_kasus',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='kasus',
            name='icd_10',
        ),
        migrations.RemoveField(
            model_name='kasus',
            name='kat_pasien',
        ),
        migrations.RemoveField(
            model_name='kasus',
            name='kode',
        ),
        migrations.DeleteModel(
            name='Indeks',
        ),
        migrations.DeleteModel(
            name='Jumlah_Kasus',
        ),
        migrations.DeleteModel(
            name='Kasus',
        ),
    ]
