# Generated by Django 3.0.3 on 2020-04-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_trialv12', '0012_auto_20200410_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indeks',
            fields=[
                ('kode', models.AutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('deleted', models.IntegerField()),
                ('last_upload', models.IntegerField()),
                ('kode_pkm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Puskesmas')),
            ],
        ),
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasus_baru', models.IntegerField()),
                ('kasus_lama', models.IntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Subkategori')),
                ('kat_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Indeks')),
            ],
        ),
        migrations.CreateModel(
            name='Jumlah_Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_baru_l', models.IntegerField()),
                ('jumlah_baru_p', models.IntegerField()),
                ('jumlah_lama_l', models.IntegerField()),
                ('jumlah_lama_p', models.IntegerField()),
                ('gakin', models.IntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.ICD10_Subkategori')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv12.Indeks')),
            ],
        ),
    ]
