# Generated by Django 3.0.3 on 2020-04-28 20:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPuskesmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('descriptio', models.CharField(max_length=254)),
                ('timestamp', models.CharField(max_length=24)),
                ('begin', models.CharField(max_length=24)),
                ('end', models.CharField(max_length=24)),
                ('altitudemo', models.CharField(max_length=254)),
                ('tessellate', models.BigIntegerField()),
                ('extrude', models.BigIntegerField()),
                ('visibility', models.BigIntegerField()),
                ('draworder', models.BigIntegerField()),
                ('icon', models.CharField(max_length=254)),
                ('layer', models.CharField(max_length=254)),
                ('path', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_Chapter',
            fields=[
                ('chapter', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nama_chapter', models.CharField(max_length=149)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_Kategori',
            fields=[
                ('kat', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_kat', models.CharField(max_length=199)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_Subkategori',
            fields=[
                ('subkat', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nama_subkat', models.CharField(max_length=99)),
                ('kat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.ICD10_Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Indeks',
            fields=[
                ('kode', models.SmallAutoField(primary_key=True, serialize=False)),
                ('tanggal', models.DateField()),
                ('deleted', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('kode_kec', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_kec', models.CharField(max_length=25)),
                ('lat_kec', models.FloatField(null=True)),
                ('longt_kec', models.FloatField(null=True)),
                ('pddk_l', models.PositiveIntegerField()),
                ('pddk_p', models.PositiveIntegerField()),
                ('jml_pddk', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasien',
            fields=[
                ('kat_pasien', models.SmallAutoField(primary_key=True, serialize=False)),
                ('umur', models.CharField(max_length=10)),
                ('jenis_kelamin', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TitikPuskesmas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.BigIntegerField()),
                ('puskesmas', models.CharField(max_length=254)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Puskesmas',
            fields=[
                ('kode_pkm', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('nama_pkm', models.CharField(max_length=30)),
                ('lat_pkm', models.FloatField(null=True)),
                ('longt_pkm', models.FloatField(null=True)),
                ('kode_kec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.Kecamatan')),
            ],
        ),
        migrations.CreateModel(
            name='Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasus_baru', models.PositiveSmallIntegerField()),
                ('kasus_lama', models.PositiveSmallIntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.ICD10_Subkategori')),
                ('kat_pasien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.Pasien')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.Indeks')),
            ],
        ),
        migrations.CreateModel(
            name='Jumlah_Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_kat', models.PositiveIntegerField()),
                ('kat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.ICD10_Kategori')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.Indeks')),
            ],
        ),
        migrations.CreateModel(
            name='Jumlah_Kasus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_baru_l', models.PositiveSmallIntegerField()),
                ('jumlah_baru_p', models.PositiveSmallIntegerField()),
                ('jumlah_lama_l', models.PositiveSmallIntegerField()),
                ('jumlah_lama_p', models.PositiveSmallIntegerField()),
                ('jumlah', models.PositiveSmallIntegerField()),
                ('gakin', models.PositiveSmallIntegerField()),
                ('icd_10', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.ICD10_Subkategori')),
                ('kode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.Indeks')),
            ],
        ),
        migrations.AddField(
            model_name='indeks',
            name='kode_pkm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.Puskesmas'),
        ),
        migrations.CreateModel(
            name='ICD10_Subchapter',
            fields=[
                ('subchapter', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nama_subchapter', models.CharField(max_length=199)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.ICD10_Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='icd10_kategori',
            name='subchapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_trialv17.ICD10_Subchapter'),
        ),
    ]
